# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarjadas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=50, verbose_name='Placa')),
            ],
            options={
                'verbose_name': 'Camión',
                'verbose_name_plural': 'Camiones',
            },
        ),
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Carga',
                'verbose_name_plural': 'Cargas',
            },
        ),
        migrations.AddField(
            model_name='camion',
            name='cargas',
            field=models.ManyToManyField(related_name='camion_cargas', to='tarjadas.Carga'),
        ),
        migrations.AddField(
            model_name='camion',
            name='chofer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='camion_chofer', to='tarjadas.Chofer'),
        ),
    ]
