# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 18:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tarjadas', '0002_auto_20160726_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='highlighted',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chofer',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='choferes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
